import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of use · conjecture-ai",
  alternates: { canonical: "/terms" },
};

const LAST_UPDATED = "October 8, 2026";

export default function Terms() {
  return (
    <main className="mx-auto max-w-2xl px-6 py-10 space-y-5 text-sm leading-relaxed">
      <header>
        <Link href="/" className="muted text-xs underline underline-offset-2 hover:no-underline">
          ← conjecture-ai
        </Link>
        <h1 className="text-xl font-semibold tracking-tight mt-3">Terms of use</h1>
        <p className="muted text-xs mt-1">Last updated {LAST_UPDATED}</p>
      </header>

      <p>
        By using conjecture-ai you agree to these terms. If you do not agree, please do not
        use it.
      </p>

      <section className="space-y-2">
        <h2 className="font-medium">Your data</h2>
        <p>
          The datasets you load are processed entirely in your browser. They are not uploaded
          to us. To generate hypotheses, your browser sends a statistical profile of your
          tables (column names, types, counts, ranges and masked format shapes, but no cell
          values) directly to Anthropic. On later rounds it also sends pass/fail counts of the
          checks already run. You can inspect each request in the app.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="font-medium">Your API key</h2>
        <p>
          You supply your own Anthropic API key. It is saved in your browser&apos;s local
          storage and sent only to Anthropic, directly from your browser. We never receive or
          store it. Anyone with access to your browser profile can read it, so use
          &ldquo;Forget key&rdquo; on shared devices.
        </p>
        <p>
          You are responsible for your key and for all usage and charges on your Anthropic
          account. Your use of Anthropic&apos;s API is governed by Anthropic&apos;s own terms
          and policies.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="font-medium">Acceptable use</h2>
        <p>
          Only load data you have the right to process, and do not use this tool for anything
          unlawful or in violation of Anthropic&apos;s usage policies.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="font-medium">No warranty</h2>
        <p>
          conjecture-ai is provided &ldquo;as is&rdquo;, without warranty of any kind. Its
          hypotheses are generated by an AI model and its results may be incomplete or wrong.
          Verify anything that matters before relying on it. To the fullest extent permitted by
          law, we are not liable for any loss or damage arising from its use.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="font-medium">Changes</h2>
        <p>
          We may update these terms. The date above shows when they last changed, and
          continuing to use the tool after a change means you accept the updated terms.
        </p>
      </section>
    </main>
  );
}
