import Anthropic from "@anthropic-ai/sdk";
import { zodOutputFormat } from "@anthropic-ai/sdk/helpers/zod";
import { Hono } from "hono";
import { cors } from "hono/cors";
import { TableProfileSchema } from "@/lib/profile/types";
import { WireHypothesesSchema, normalizeHypotheses } from "@/lib/hypotheses/schema";
import { SYSTEM_PROMPT, buildUserMessage } from "./prompt";

interface Env {
  ANTHROPIC_API_KEY: string;
  ENVIRONMENT?: string;
}

/**
 * The entire server. It holds the API key, and nothing else.
 *
 * It is deliberately stateless and accepts only a profile: the system prompt,
 * output schema, model and token cap are all server-owned, so this endpoint
 * cannot be repurposed as a general-purpose Claude proxy by anyone who gets
 * past Cloudflare Access.
 */
const MODEL = "claude-sonnet-5";
const MAX_TOKENS = 16_000;
const MAX_BODY_BYTES = 2 * 1024 * 1024;

const app = new Hono<{ Bindings: Env }>();

/**
 * Static assets get these from public/_headers, which does not apply to
 * responses generated by Worker code — so set them here too.
 */
app.use("*", async (c, next) => {
  await next();
  c.header("X-Robots-Tag", "noindex, nofollow, noarchive, nosnippet");
  c.header("Referrer-Policy", "no-referrer");
});

// In development the static site is on :3000 and this Worker on :8787.
// In production they share an origin and this middleware does nothing.
app.use("/api/*", async (c, next) => {
  if (c.env.ENVIRONMENT !== "production") {
    return cors({
      origin: ["http://localhost:3000", "http://127.0.0.1:3000"],
      allowMethods: ["POST", "GET", "OPTIONS"],
      allowHeaders: ["Content-Type"],
    })(c, next);
  }
  await next();
});

app.get("/api/health", (c) =>
  c.json({ ok: true, model: MODEL, hasKey: Boolean(c.env.ANTHROPIC_API_KEY) }),
);

app.post("/api/hypotheses", async (c) => {
  if (!c.env.ANTHROPIC_API_KEY) {
    return c.json({ error: "ANTHROPIC_API_KEY is not configured on the server." }, 500);
  }

  const declaredLength = Number(c.req.header("content-length") ?? 0);
  if (declaredLength > MAX_BODY_BYTES) {
    return c.json({ error: "Profile too large." }, 413);
  }

  let body: unknown;
  try {
    body = await c.req.json();
  } catch {
    return c.json({ error: "Body must be JSON." }, 400);
  }

  // Parsing here also strips any key the schema does not declare, so a client
  // cannot smuggle extra fields through to the model.
  const parsed = TableProfileSchema.safeParse((body as { profile?: unknown })?.profile);
  if (!parsed.success) {
    return c.json(
      { error: "Invalid profile.", detail: parsed.error.issues.slice(0, 5) },
      400,
    );
  }
  const profile = parsed.data;

  const client = new Anthropic({ apiKey: c.env.ANTHROPIC_API_KEY });

  try {
    const response = await client.messages.parse({
      model: MODEL,
      max_tokens: MAX_TOKENS,
      system: SYSTEM_PROMPT,
      messages: [{ role: "user", content: buildUserMessage(profile) }],
      output_config: { format: zodOutputFormat(WireHypothesesSchema) },
    });

    if (response.stop_reason === "refusal") {
      return c.json({ error: "The model declined to answer this request." }, 422);
    }
    if (!response.parsed_output) {
      return c.json({ error: "The model did not return a usable result." }, 502);
    }

    return c.json({
      hypotheses: normalizeHypotheses(response.parsed_output),
      usage: {
        inputTokens: response.usage.input_tokens,
        outputTokens: response.usage.output_tokens,
      },
    });
  } catch (err) {
    if (err instanceof Anthropic.RateLimitError) {
      return c.json({ error: "Rate limited by Anthropic. Try again shortly." }, 429);
    }
    if (err instanceof Anthropic.AuthenticationError) {
      return c.json({ error: "Anthropic rejected the API key." }, 502);
    }
    if (err instanceof Anthropic.APIConnectionError) {
      return c.json({ error: "Could not reach Anthropic." }, 504);
    }
    if (err instanceof Anthropic.APIError) {
      return c.json({ error: `Anthropic returned ${err.status ?? "an error"}.` }, 502);
    }
    console.error("hypotheses failed", err);
    return c.json({ error: "Unexpected server error." }, 500);
  }
});

app.notFound((c) => c.json({ error: "Not found" }, 404));

export default app;
